### ISSUE TITLE
Unknown resampling_method: sinc_interp_kaiser

### ISSUE THREAD

**Issue by cocolab8** [rhasspy/piper-sample-generator#10]
I got the error message "Unknown resampling_method: sinc_interp_kaiser".
I did solve it as shown by the following diff:

--- a/generate_samples.py
+++ b/generate_samples.py
@@ -115,7 +115,7 @@ def generate_samples(
         resample_rate,
         lowpass_filter_width=64,
         rolloff=0.9475937167399596,
-        resampling_method="sinc_interp_kaiser",
+        resampling_method="sinc_interpolation",
         beta=14.769656459379492,
     )

**Comment by SleepInfinity** [comment]
same problem.
```
Traceback (most recent call last):
  File "/root/piper-sample-generator/generate_samples.py", line 481, in <module>
    main()
  File "/root/piper-sample-generator/generate_samples.py", line 477, in main
    generate_samples(**args)
  File "/root/piper-sample-generator/generate_samples.py", line 113, in generate_samples
    resampler = torchaudio.transforms.Resample(
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/transforms/_transforms.py", line 980, in __init__
    kernel, self.width = _get_sinc_resample_kernel(
  File "/usr/local/lib/python3.10/dist-packages/torchaudio/functional/functional.py", line 1449, in _get_sinc_resample_kernel
    raise ValueError("Invalid resampling method: {}".format(resampling_method))
ValueError: Invalid resampling method: sinc_interp_kaiser
```

**Comment by gyaneesh** [comment]
issue is due to incorrect torch package reference, mostly likely lower than 2.5.0

**Comment by danielBreitlauch** [comment]
For me it is
```
ValueError: Invalid resampling method: sinc_interp_kaiser
```

I have 
```
torch-1.13.1.dist-info
torchaudio-0.13.1.dist-info
```

What torch version is the right one? https://github.com/rhasspy/piper-sample-generator/blob/9c1019c932eda098aa70d63cdeac803dea983f53/requirements.txt#L4

It could also be helpful to mention the python restrictions resulting from all the package restrictions. Python must be 3.10 right?
In general, a pyproject.toml declaring everything could do it.

**Comment by synesthesiam** [comment]
Resampling has been removed in v3: https://github.com/rhasspy/piper-sample-generator/releases/tag/v3.0.0
